### ISSUE TITLE
Is it possible to generate ddl from json?

### ISSUE THREAD

**Issue by jrichardsz** [duartealexf/sql-ddl-to-json-schema#64]
What about the opposite: Create DDL from json.

Is it possible?

**Comment by glaucoleme** [comment]
I've found [this website](https://www.convertjson.com/json-to-sql.htm) that is possible to get the DLL and others CRUD SQL codes from a JSON sample. 

As is instantaneous to generate a JSON sample from an JSON schema, this tool could be helpful. The options of the interface to edit the query are quite convenient as well.

But taking an schema as input would be way more optimal as it could take in consideration the value validation options of the schema to establish the correct data types. Maybe there is already an specific tool that receives a JSON schema as input, but I did not have time enough to dig throughout the web to find it.

I have interest to collaborate in this tool, whether exist.

**Comment by duartealexf** [comment]
Hi @jrichardsz and @glaucoleme you're not the first to ask about such feature (see #58 and #57 [comment](https://github.com/duartealexf/sql-ddl-to-json-schema/issues/57#issuecomment-612193119)).

Creating DDL from JSON is currently out of scope of this project, simply because I would not have the time to dedicate for it... unless you're willing to contribute?

Also, please let me know if you do find an already existing tool that creates DDL from JSON, and if a creating a JSON Schema would help. As this is a recurring question this would definitely help for those looking for such feature.

**Comment by duartealexf** [comment]
I didn't get any replies so I'm going to close this for now.
