### ISSUE TITLE
convert to json-schema 04

### ISSUE THREAD

**Issue by MiguelSequeiros** [duartealexf/sql-ddl-to-json-schema#77]
Is it possible? any workarround?
Actually, it's converting to draft 07

**Comment by duartealexf** [comment]
Sorry for taking forever to reply to this.

There is no support to convert to JSON Schema draft 04.
You could probably just change the `$schema` property to point to draft 04 and it should all work. Any properties that are in draft 07 but not in draft 04 (e.g. `$id`, `$comment`) should be ignored, so it would still be ok because there is no negative validation against them.

A workaround I see is:

```js
const convertJsonSchema07To04 = ({
  $schema,
  ...doc,
}) => ({
  $schema: 'http://json-schema.org/draft-04/schema',
  ...doc,
})

const jsonSchemaDocuments = parser.feed(sql).toJsonSchemaArray({ useRef: false });

const draft04JsonSchemaDocs = jsonSchemaDocuments.map(convertJsonSchema07To04);
```

I have not tested the code above but theoretically it should be enough. Please let me know.

This is based on the JSON Schema changelogs I saw [here](https://json-schema.org/draft-06/json-schema-release-notes.html) and [here](https://json-schema.org/draft-07/json-schema-release-notes.html).
